// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/powerplatform/services/environment/resource_environment.go

// Package mock_environment is a generated GoMock package.
package mock_environment
